trigger:
- master

pool:
  name: self-hosted_1

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
        npm install cypress --save-dev
        npm install mocha-junit-reporter --save-dev
      displayName: 'Install Dependencies and Cypress'

    # Publish Cypress tests as artifacts
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(System.DefaultWorkingDirectory)/cypress/e2e'
        artifactName: 'cypress-tests'
        publishLocation: 'Container'

- stage: Cypress_Tests
  dependsOn: Build
  jobs:
  - job: OpenWiki
    displayName: 'Open Wiki'
    steps:
    # Download Cypress tests artifact from Build stage
    - download: current
      artifact: cypress-tests
    - script: |
        cd $(System.DefaultWorkingDirectory)/cypress/e2e/1-open-wiki
        npm run cypress:run:open-wiki
      displayName: 'Run Cypress Tests'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/test-results.xml'

  - job: CheckWiki
    displayName: 'Check Wiki'
    steps:
    # Download Cypress tests artifact from Build stage
    - download: current
      artifact: cypress-tests
    - script: |
        cd $(System.DefaultWorkingDirectory)/cypress/e2e/2-check-wiki
        npm run cypress:run:check-wiki
      displayName: 'Run Cypress Tests'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/test-results.xml'
