trigger:
- master

pool:
  vmImage: windows-latest

steps:
- script: |
    npm install -g yarn
  displayName: 'Install Yarn'

- script: |
    pwd
    ls -al
  displayName: 'Debug Information'

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run test'
  continueOnError: true

- script: |
    cd $(System.DefaultWorkingDirectory)/cypress
    npm test
  displayName: 'Run Cypress Tests'
