trigger:
- master

pool:
  name: self-hosted_1

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
      displayName: 'npm install and build'
    - script: |
        npm install cypress --save-dev
      displayName: 'npm install Cypress'
    - script: |
        npm install mocha-junit-reporter --save-dev
      displayName: 'npm install mocha-junit-reporter'
    - script: |
        npm run cypress:open -- --config video=false
      displayName: 'Open Cypress'

- stage: 1-open-wiki
  dependsOn: Build
  jobs:
  - job: TestJob
    steps:
    - download: current
      artifact: drop
    - script: |
        cd $(System.DefaultWorkingDirectory)/cypress/e2e/1-open-wiki
        npm run cypress:run
      displayName: 'Run Cypress Tests'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/test-results.xml'
      
- stage: 2-check-wiki
  dependsOn: Build
  jobs:
  - job: TestJob
    steps:
    - download: current
      artifact: drop
    - script: |
        cd $(System.DefaultWorkingDirectory)/cypress/e2e/2-check-wiki
        npm run cypress:run
      displayName: 'Run Cypress Tests'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/test-results.xml'