trigger:
- master

pool:
  name: self-hosted_1

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
      displayName: 'npm install and build'

- stage: Test
  jobs:
  - job: TestJob
    steps:
    - script: |
        npm install mocha-junit-reporter --save-dev
      displayName: 'npm install mocha-junit-reporter'
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run test'
      continueOnError: true
    - script: |
        cd $(System.DefaultWorkingDirectory)/cypress
        npm test
      displayName: 'Run Cypress Tests'

- stage: Publish
  jobs:
  - job: PublishJob
    steps:
    - script: npm run cypress:run
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/test-results.xml'  